### ISSUE TITLE
Support Composer v2.2+

### ISSUE THREAD

**Issue by Szasza** [dev-this/satis-build#1]
## Issue

In Composer v2.2.0 a new security-related configuration option was added, [allow-plugins](https://getcomposer.org/doc/06-config.md#allow-plugins). As in [this line](https://github.com/dev-this/satis-build/blob/master/action.yaml#L21) an empty Composer config is created, and there is no way to intervene at the moment in any way for that to be used as-is, it renders this action unusable with the currently latest version of Composer and Satis.

## Expected behaviour

The action works on all supported Composer and Satis versions.

**Comment by VeryStrongFingers** [comment]
I am fairly out of touch when it comes to PHP and Composer these days. Would you mind doing a PR?

**Comment by Szasza** [comment]
@VeryStrongFingers thank you for the comment, the PR is open.
